module.exports = {
  "apps": [
    {
      "name": "miner1",
      "script": "run_miner.py",
      "interpreter": "/root/sn90_tien/.venv/bin/python3",
      "cwd": "/root/sn90_tien",
      "env": {
        "NETWORK": "finney",
        "SUBNET_UID": "90",
        "API_URL": "https://api.subnet90.com",
        "LOG_LEVEL": "DEBUG",
        "LOG_FORMAT": "json",
        "LOG_DIR": "./logs",
        "MAX_WORKERS": "4",
        "REQUEST_TIMEOUT": "30",
        "WALLET_NAME": "c1",
        "HOTKEY_NAME": "h1",
        "MINER_PORT": "9001",
        "MINER_STRATEGY": "ai_reasoning",
        "MINER_ID": "miner1"
      },
      "error_file": "./logs/miner1.error.log",
      "out_file": "./logs/miner1.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "max_restarts": 10,
      "min_uptime": "10s",
      "restart_delay": 4000,
      "autorestart": true,
      "watch": false
    },
    {
      "name": "miner2",
      "script": "run_miner.py",
      "interpreter": "/root/sn90_tien/.venv/bin/python3",
      "cwd": "/root/sn90_tien",
      "env": {
        "NETWORK": "finney",
        "SUBNET_UID": "90",
        "API_URL": "https://api.subnet90.com",
        "LOG_LEVEL": "DEBUG",
        "LOG_FORMAT": "json",
        "LOG_DIR": "./logs",
        "MAX_WORKERS": "4",
        "REQUEST_TIMEOUT": "30",
        "WALLET_NAME": "c1",
        "HOTKEY_NAME": "h2",
        "MINER_PORT": "9002",
        "MINER_STRATEGY": "ai_reasoning",
        "MINER_ID": "miner2"
      },
      "error_file": "./logs/miner2.error.log",
      "out_file": "./logs/miner2.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "max_restarts": 10,
      "min_uptime": "10s",
      "restart_delay": 4000,
      "autorestart": true,
      "watch": false
    },
    {
      "name": "miner3",
      "script": "run_miner.py",
      "interpreter": "/root/sn90_tien/.venv/bin/python3",
      "cwd": "/root/sn90_tien",
      "env": {
        "NETWORK": "finney",
        "SUBNET_UID": "90",
        "API_URL": "https://api.subnet90.com",
        "LOG_LEVEL": "DEBUG",
        "LOG_FORMAT": "json",
        "LOG_DIR": "./logs",
        "MAX_WORKERS": "4",
        "REQUEST_TIMEOUT": "30",
        "WALLET_NAME": "c1",
        "HOTKEY_NAME": "h3",
        "MINER_PORT": "9003",
        "MINER_STRATEGY": "ai_reasoning",
        "MINER_ID": "miner3"
      },
      "error_file": "./logs/miner3.error.log",
      "out_file": "./logs/miner3.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "max_restarts": 10,
      "min_uptime": "10s",
      "restart_delay": 4000,
      "autorestart": true,
      "watch": false
    },
    {
      "name": "miner4",
      "script": "run_miner.py",
      "interpreter": "/root/sn90_tien/.venv/bin/python3",
      "cwd": "/root/sn90_tien",
      "env": {
        "NETWORK": "finney",
        "SUBNET_UID": "90",
        "API_URL": "https://api.subnet90.com",
        "LOG_LEVEL": "DEBUG",
        "LOG_FORMAT": "json",
        "LOG_DIR": "./logs",
        "MAX_WORKERS": "4",
        "REQUEST_TIMEOUT": "30",
        "WALLET_NAME": "c1",
        "HOTKEY_NAME": "h4",
        "MINER_PORT": "9004",
        "MINER_STRATEGY": "ai_reasoning",
        "MINER_ID": "miner4"
      },
      "error_file": "./logs/miner4.error.log",
      "out_file": "./logs/miner4.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "max_restarts": 10,
      "min_uptime": "10s",
      "restart_delay": 4000,
      "autorestart": true,
      "watch": false
    }
  ]
}